version: '3'

services:
  nextjs-docker:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    image: nextjs-docker
    ports:
      - '3001:3000'
  postgres_dev:
    container_name: 'postgres-dev'
    image: 'postgres:14.1-alpine'
    env_file:
      - ../.env
    ports:
      - '54320:5432'
    volumes:
      - postgres_data:/data/postgres
    restart: unless-stopped

volumes:
  postgres_data: